#!/opt/python3/bin/python3
# @@ AVID HEADER - DO NOT EDIT @@
# Copyright 2013-2014 by Avid Technology, Inc.
# @@ AVID HEADER @@

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configtd2_main.ui'
#
# Created: Fri Apr  4 16:44:41 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.storage_panel = QtGui.QWidget()
        self.storage_panel.setObjectName(_fromUtf8("storage_panel"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.storage_panel)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.mount_data_group_box = QtGui.QGroupBox(self.storage_panel)
        self.mount_data_group_box.setObjectName(_fromUtf8("mount_data_group_box"))
        self.formLayout = QtGui.QFormLayout(self.mount_data_group_box)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.user_label = QtGui.QLabel(self.mount_data_group_box)
        self.user_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.user_label.setObjectName(_fromUtf8("user_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.user_label)
        self.mount_user_box = QtGui.QLineEdit(self.mount_data_group_box)
        self.mount_user_box.setObjectName(_fromUtf8("mount_user_box"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.mount_user_box)
        self.mount_passwd_box = QtGui.QLineEdit(self.mount_data_group_box)
        self.mount_passwd_box.setObjectName(_fromUtf8("mount_passwd_box"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mount_passwd_box)
        self.scratch_dir_box = QtGui.QLineEdit(self.mount_data_group_box)
        self.scratch_dir_box.setObjectName(_fromUtf8("scratch_dir_box"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.scratch_dir_box)
        self.password_label = QtGui.QLabel(self.mount_data_group_box)
        self.password_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.password_label.setObjectName(_fromUtf8("password_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.password_label)
        self.scratch_label = QtGui.QLabel(self.mount_data_group_box)
        self.scratch_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scratch_label.setObjectName(_fromUtf8("scratch_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.scratch_label)
        self.mount_label = QtGui.QLabel(self.mount_data_group_box)
        self.mount_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mount_label.setObjectName(_fromUtf8("mount_label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.mount_label)
        self.enable_mount_box = QtGui.QCheckBox(self.mount_data_group_box)
        self.enable_mount_box.setObjectName(_fromUtf8("enable_mount_box"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.enable_mount_box)
        self.verticalLayout_5.addWidget(self.mount_data_group_box)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.primary_unity_group_box = QtGui.QGroupBox(self.storage_panel)
        self.primary_unity_group_box.setObjectName(_fromUtf8("primary_unity_group_box"))
        self.formLayout_2 = QtGui.QFormLayout(self.primary_unity_group_box)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.servername_label = QtGui.QLabel(self.primary_unity_group_box)
        self.servername_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.servername_label.setObjectName(_fromUtf8("servername_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.servername_label)
        self.workspace_label = QtGui.QLabel(self.primary_unity_group_box)
        self.workspace_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.workspace_label.setObjectName(_fromUtf8("workspace_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.workspace_label)
        self.storagegroup_label = QtGui.QLabel(self.primary_unity_group_box)
        self.storagegroup_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.storagegroup_label.setObjectName(_fromUtf8("storagegroup_label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.storagegroup_label)
        self.network_label = QtGui.QLabel(self.primary_unity_group_box)
        self.network_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.network_label.setObjectName(_fromUtf8("network_label"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.network_label)
        self.server_box1 = QtGui.QLineEdit(self.primary_unity_group_box)
        self.server_box1.setObjectName(_fromUtf8("server_box1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.server_box1)
        self.workspace_box1 = QtGui.QLineEdit(self.primary_unity_group_box)
        self.workspace_box1.setObjectName(_fromUtf8("workspace_box1"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.workspace_box1)
        self.storage_group_box1 = QtGui.QLineEdit(self.primary_unity_group_box)
        self.storage_group_box1.setObjectName(_fromUtf8("storage_group_box1"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.storage_group_box1)
        self.np_combobox1 = QtGui.QComboBox(self.primary_unity_group_box)
        self.np_combobox1.setObjectName(_fromUtf8("np_combobox1"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.np_combobox1)
        self.verticalLayout_5.addWidget(self.primary_unity_group_box)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.quality_center_group_box = QtGui.QGroupBox(self.storage_panel)
        self.quality_center_group_box.setObjectName(_fromUtf8("quality_center_group_box"))
        self.formLayout_3 = QtGui.QFormLayout(self.quality_center_group_box)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.remoteclient_label = QtGui.QLabel(self.quality_center_group_box)
        self.remoteclient_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remoteclient_label.setObjectName(_fromUtf8("remoteclient_label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.remoteclient_label)
        self.remote_client_box = QtGui.QLineEdit(self.quality_center_group_box)
        self.remote_client_box.setObjectName(_fromUtf8("remote_client_box"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.remote_client_box)
        self.verticalLayout_6.addWidget(self.quality_center_group_box)
        self.test_behaviour_group_box = QtGui.QGroupBox(self.storage_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_behaviour_group_box.sizePolicy().hasHeightForWidth())
        self.test_behaviour_group_box.setSizePolicy(sizePolicy)
        self.test_behaviour_group_box.setObjectName(_fromUtf8("test_behaviour_group_box"))
        self.gridLayout = QtGui.QGridLayout(self.test_behaviour_group_box)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stop_label = QtGui.QLabel(self.test_behaviour_group_box)
        self.stop_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stop_label.setObjectName(_fromUtf8("stop_label"))
        self.gridLayout.addWidget(self.stop_label, 0, 0, 1, 1)
        self.developer_label = QtGui.QLabel(self.test_behaviour_group_box)
        self.developer_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.developer_label.setObjectName(_fromUtf8("developer_label"))
        self.gridLayout.addWidget(self.developer_label, 1, 0, 1, 1)
        self.logging_label = QtGui.QLabel(self.test_behaviour_group_box)
        self.logging_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logging_label.setObjectName(_fromUtf8("logging_label"))
        self.gridLayout.addWidget(self.logging_label, 2, 0, 1, 1)
        self.sotf_box = QtGui.QCheckBox(self.test_behaviour_group_box)
        self.sotf_box.setObjectName(_fromUtf8("sotf_box"))
        self.gridLayout.addWidget(self.sotf_box, 0, 1, 1, 1)
        self.devmode_box = QtGui.QCheckBox(self.test_behaviour_group_box)
        self.devmode_box.setObjectName(_fromUtf8("devmode_box"))
        self.gridLayout.addWidget(self.devmode_box, 1, 1, 1, 1)
        self.log_settings_box = QtGui.QCheckBox(self.test_behaviour_group_box)
        self.log_settings_box.setObjectName(_fromUtf8("log_settings_box"))
        self.gridLayout.addWidget(self.log_settings_box, 2, 1, 1, 1)
        self.log_value_box = QtGui.QLineEdit(self.test_behaviour_group_box)
        self.log_value_box.setObjectName(_fromUtf8("log_value_box"))
        self.gridLayout.addWidget(self.log_value_box, 2, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.test_behaviour_group_box)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.second_unity_group_box = QtGui.QGroupBox(self.storage_panel)
        self.second_unity_group_box.setObjectName(_fromUtf8("second_unity_group_box"))
        self.formLayout_4 = QtGui.QFormLayout(self.second_unity_group_box)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.servername_label_2 = QtGui.QLabel(self.second_unity_group_box)
        self.servername_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.servername_label_2.setObjectName(_fromUtf8("servername_label_2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.servername_label_2)
        self.server_box2 = QtGui.QLineEdit(self.second_unity_group_box)
        self.server_box2.setObjectName(_fromUtf8("server_box2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.server_box2)
        self.workspace_label_2 = QtGui.QLabel(self.second_unity_group_box)
        self.workspace_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.workspace_label_2.setObjectName(_fromUtf8("workspace_label_2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.workspace_label_2)
        self.workspace_box2 = QtGui.QLineEdit(self.second_unity_group_box)
        self.workspace_box2.setObjectName(_fromUtf8("workspace_box2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.workspace_box2)
        self.storagegroup_label_2 = QtGui.QLabel(self.second_unity_group_box)
        self.storagegroup_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.storagegroup_label_2.setObjectName(_fromUtf8("storagegroup_label_2"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.storagegroup_label_2)
        self.storage_group_box2 = QtGui.QLineEdit(self.second_unity_group_box)
        self.storage_group_box2.setObjectName(_fromUtf8("storage_group_box2"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.storage_group_box2)
        self.network_label_2 = QtGui.QLabel(self.second_unity_group_box)
        self.network_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.network_label_2.setObjectName(_fromUtf8("network_label_2"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.network_label_2)
        self.np_combobox2 = QtGui.QComboBox(self.second_unity_group_box)
        self.np_combobox2.setObjectName(_fromUtf8("np_combobox2"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.np_combobox2)
        self.verticalLayout_6.addWidget(self.second_unity_group_box)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.storage_panel, _fromUtf8(""))
        self.isis_panel = QtGui.QWidget()
        self.isis_panel.setObjectName(_fromUtf8("isis_panel"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.isis_panel)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.isisdata_group = QtGui.QGroupBox(self.isis_panel)
        self.isisdata_group.setObjectName(_fromUtf8("isisdata_group"))
        self.formLayout_5 = QtGui.QFormLayout(self.isisdata_group)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.mcu_label = QtGui.QLabel(self.isisdata_group)
        self.mcu_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mcu_label.setObjectName(_fromUtf8("mcu_label"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.mcu_label)
        self.mcu_text = QtGui.QLineEdit(self.isisdata_group)
        self.mcu_text.setObjectName(_fromUtf8("mcu_text"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.mcu_text)
        self.mcp_label = QtGui.QLabel(self.isisdata_group)
        self.mcp_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mcp_label.setObjectName(_fromUtf8("mcp_label"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.mcp_label)
        self.sbu_label = QtGui.QLabel(self.isisdata_group)
        self.sbu_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbu_label.setObjectName(_fromUtf8("sbu_label"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.sbu_label)
        self.sbp_label = QtGui.QLabel(self.isisdata_group)
        self.sbp_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbp_label.setObjectName(_fromUtf8("sbp_label"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.sbp_label)
        self.mcp_text = QtGui.QLineEdit(self.isisdata_group)
        self.mcp_text.setObjectName(_fromUtf8("mcp_text"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.mcp_text)
        self.sbu_text = QtGui.QLineEdit(self.isisdata_group)
        self.sbu_text.setObjectName(_fromUtf8("sbu_text"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.sbu_text)
        self.sbp_text = QtGui.QLineEdit(self.isisdata_group)
        self.sbp_text.setObjectName(_fromUtf8("sbp_text"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.sbp_text)
        self.verticalLayout_8.addWidget(self.isisdata_group)
        self.ftp_group = QtGui.QGroupBox(self.isis_panel)
        self.ftp_group.setObjectName(_fromUtf8("ftp_group"))
        self.formLayout_6 = QtGui.QFormLayout(self.ftp_group)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.ftpserver_label = QtGui.QLabel(self.ftp_group)
        self.ftpserver_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ftpserver_label.setObjectName(_fromUtf8("ftpserver_label"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.ftpserver_label)
        self.ftp_loginname_label = QtGui.QLabel(self.ftp_group)
        self.ftp_loginname_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ftp_loginname_label.setObjectName(_fromUtf8("ftp_loginname_label"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.ftp_loginname_label)
        self.ftp_password_label = QtGui.QLabel(self.ftp_group)
        self.ftp_password_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ftp_password_label.setObjectName(_fromUtf8("ftp_password_label"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.ftp_password_label)
        self.ftpserver_text = QtGui.QLineEdit(self.ftp_group)
        self.ftpserver_text.setObjectName(_fromUtf8("ftpserver_text"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.ftpserver_text)
        self.ftp_loginname_text = QtGui.QLineEdit(self.ftp_group)
        self.ftp_loginname_text.setObjectName(_fromUtf8("ftp_loginname_text"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.ftp_loginname_text)
        self.ftp_password_text = QtGui.QLineEdit(self.ftp_group)
        self.ftp_password_text.setObjectName(_fromUtf8("ftp_password_text"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.ftp_password_text)
        self.verticalLayout_8.addWidget(self.ftp_group)
        self.licensing_group = QtGui.QGroupBox(self.isis_panel)
        self.licensing_group.setObjectName(_fromUtf8("licensing_group"))
        self.formLayout_7 = QtGui.QFormLayout(self.licensing_group)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.system_id_label = QtGui.QLabel(self.licensing_group)
        self.system_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.system_id_label.setObjectName(_fromUtf8("system_id_label"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.system_id_label)
        self.system_id_text = QtGui.QLineEdit(self.licensing_group)
        self.system_id_text.setObjectName(_fromUtf8("system_id_text"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.system_id_text)
        self.activation_id_label = QtGui.QLabel(self.licensing_group)
        self.activation_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.activation_id_label.setObjectName(_fromUtf8("activation_id_label"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.activation_id_label)
        self.activation_id_text = QtGui.QLineEdit(self.licensing_group)
        self.activation_id_text.setObjectName(_fromUtf8("activation_id_text"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.activation_id_text)
        self.verticalLayout_8.addWidget(self.licensing_group)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem3)
        self.groupBox = QtGui.QGroupBox(self.isis_panel)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_12 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_12.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.sb_activation_id_label = QtGui.QLabel(self.groupBox)
        self.sb_activation_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_activation_id_label.setObjectName(_fromUtf8("sb_activation_id_label"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.sb_activation_id_label)
        self.sb_system_id_text = QtGui.QLineEdit(self.groupBox)
        self.sb_system_id_text.setObjectName(_fromUtf8("sb_system_id_text"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.sb_system_id_text)
        self.sb_activation_id_text = QtGui.QLineEdit(self.groupBox)
        self.sb_activation_id_text.setObjectName(_fromUtf8("sb_activation_id_text"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.sb_activation_id_text)
        self.sb_system_id_label = QtGui.QLabel(self.groupBox)
        self.sb_system_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_system_id_label.setObjectName(_fromUtf8("sb_system_id_label"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.sb_system_id_label)
        self.verticalLayout_17.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_17)
        self.tabWidget.addTab(self.isis_panel, _fromUtf8(""))
        self.video_panel = QtGui.QWidget()
        self.video_panel.setObjectName(_fromUtf8("video_panel"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.video_panel)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.videodata_group = QtGui.QGroupBox(self.video_panel)
        self.videodata_group.setObjectName(_fromUtf8("videodata_group"))
        self.formLayout_8 = QtGui.QFormLayout(self.videodata_group)
        self.formLayout_8.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label1 = QtGui.QLabel(self.videodata_group)
        self.label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label1)
        self.text1 = QtGui.QLineEdit(self.videodata_group)
        self.text1.setObjectName(_fromUtf8("text1"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.text1)
        self.label2 = QtGui.QLabel(self.videodata_group)
        self.label2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label2)
        self.text2 = QtGui.QLineEdit(self.videodata_group)
        self.text2.setObjectName(_fromUtf8("text2"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.text2)
        self.label3 = QtGui.QLabel(self.videodata_group)
        self.label3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label3)
        self.text3 = QtGui.QLineEdit(self.videodata_group)
        self.text3.setObjectName(_fromUtf8("text3"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.text3)
        self.label4 = QtGui.QLabel(self.videodata_group)
        self.label4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.label4)
        self.story_tc_box = QtGui.QCheckBox(self.videodata_group)
        self.story_tc_box.setObjectName(_fromUtf8("story_tc_box"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.story_tc_box)
        self.label5 = QtGui.QLabel(self.videodata_group)
        self.label5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.LabelRole, self.label5)
        self.still_cue_box = QtGui.QCheckBox(self.videodata_group)
        self.still_cue_box.setObjectName(_fromUtf8("still_cue_box"))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.FieldRole, self.still_cue_box)
        self.verticalLayout_9.addWidget(self.videodata_group)
        self.storagedata_group = QtGui.QGroupBox(self.video_panel)
        self.storagedata_group.setObjectName(_fromUtf8("storagedata_group"))
        self.formLayout_9 = QtGui.QFormLayout(self.storagedata_group)
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.label1_2 = QtGui.QLabel(self.storagedata_group)
        self.label1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1_2.setObjectName(_fromUtf8("label1_2"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label1_2)
        self.use_pattern_feed = QtGui.QCheckBox(self.storagedata_group)
        self.use_pattern_feed.setObjectName(_fromUtf8("use_pattern_feed"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.use_pattern_feed)
        self.verticalLayout_9.addWidget(self.storagedata_group)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.tabWidget.addTab(self.video_panel, _fromUtf8(""))
        self.remote_panel = QtGui.QWidget()
        self.remote_panel.setObjectName(_fromUtf8("remote_panel"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.remote_panel)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalGroupBox_5 = QtGui.QGroupBox(self.remote_panel)
        self.verticalGroupBox_5.setObjectName(_fromUtf8("verticalGroupBox_5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.verticalGroupBox_5)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupcombobox = QtGui.QComboBox(self.verticalGroupBox_5)
        self.groupcombobox.setObjectName(_fromUtf8("groupcombobox"))
        self.verticalLayout_14.addWidget(self.groupcombobox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.copy_button = QtGui.QPushButton(self.verticalGroupBox_5)
        self.copy_button.setObjectName(_fromUtf8("copy_button"))
        self.horizontalLayout_4.addWidget(self.copy_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.validate_button = QtGui.QPushButton(self.verticalGroupBox_5)
        self.validate_button.setObjectName(_fromUtf8("validate_button"))
        self.horizontalLayout_4.addWidget(self.validate_button)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.hoststable = QtGui.QTableWidget(self.verticalGroupBox_5)
        self.hoststable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.hoststable.setAlternatingRowColors(True)
        self.hoststable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.hoststable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.hoststable.setShowGrid(False)
        self.hoststable.setColumnCount(2)
        self.hoststable.setObjectName(_fromUtf8("hoststable"))
        self.hoststable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.hoststable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.hoststable.setHorizontalHeaderItem(1, item)
        self.hoststable.horizontalHeader().setDefaultSectionSize(250)
        self.hoststable.horizontalHeader().setStretchLastSection(True)
        self.hoststable.verticalHeader().setVisible(False)
        self.verticalLayout_14.addWidget(self.hoststable)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.add_button = QtGui.QPushButton(self.verticalGroupBox_5)
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.horizontalLayout_5.addWidget(self.add_button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.remove_button = QtGui.QPushButton(self.verticalGroupBox_5)
        self.remove_button.setObjectName(_fromUtf8("remove_button"))
        self.horizontalLayout_5.addWidget(self.remove_button)
        self.remove_all_button = QtGui.QPushButton(self.verticalGroupBox_5)
        self.remove_all_button.setObjectName(_fromUtf8("remove_all_button"))
        self.horizontalLayout_5.addWidget(self.remove_all_button)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.verticalLayout_16.addWidget(self.verticalGroupBox_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_16)
        self.tabWidget.addTab(self.remote_panel, _fromUtf8(""))
        self.cifs_panel = QtGui.QWidget()
        self.cifs_panel.setObjectName(_fromUtf8("cifs_panel"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.cifs_panel)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.cifs_group = QtGui.QGroupBox(self.cifs_panel)
        self.cifs_group.setObjectName(_fromUtf8("cifs_group"))
        self.formLayout_10 = QtGui.QFormLayout(self.cifs_group)
        self.formLayout_10.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label1_3 = QtGui.QLabel(self.cifs_group)
        self.label1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1_3.setObjectName(_fromUtf8("label1_3"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label1_3)
        self.cifs_server_name_line_edit = QtGui.QLineEdit(self.cifs_group)
        self.cifs_server_name_line_edit.setObjectName(_fromUtf8("cifs_server_name_line_edit"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.cifs_server_name_line_edit)
        self.label2_2 = QtGui.QLabel(self.cifs_group)
        self.label2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_2.setObjectName(_fromUtf8("label2_2"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.label2_2)
        self.cifs_isis_server_line_edit = QtGui.QLineEdit(self.cifs_group)
        self.cifs_isis_server_line_edit.setObjectName(_fromUtf8("cifs_isis_server_line_edit"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.cifs_isis_server_line_edit)
        self.verticalLayout_11.addWidget(self.cifs_group)
        self.cifs_shares_group = QtGui.QGroupBox(self.cifs_panel)
        self.cifs_shares_group.setObjectName(_fromUtf8("cifs_shares_group"))
        self.formLayout_11 = QtGui.QFormLayout(self.cifs_shares_group)
        self.formLayout_11.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.label1_4 = QtGui.QLabel(self.cifs_shares_group)
        self.label1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1_4.setObjectName(_fromUtf8("label1_4"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.label1_4)
        self.cifs_share_line_edit_1 = QtGui.QLineEdit(self.cifs_shares_group)
        self.cifs_share_line_edit_1.setObjectName(_fromUtf8("cifs_share_line_edit_1"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.cifs_share_line_edit_1)
        self.label2_3 = QtGui.QLabel(self.cifs_shares_group)
        self.label2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_3.setObjectName(_fromUtf8("label2_3"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.label2_3)
        self.cifs_share_line_edit_2 = QtGui.QLineEdit(self.cifs_shares_group)
        self.cifs_share_line_edit_2.setObjectName(_fromUtf8("cifs_share_line_edit_2"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.cifs_share_line_edit_2)
        self.verticalLayout_11.addWidget(self.cifs_shares_group)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.tabWidget.addTab(self.cifs_panel, _fromUtf8(""))
        self.failover_panel = QtGui.QWidget()
        self.failover_panel.setObjectName(_fromUtf8("failover_panel"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.failover_panel)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.failover_group = QtGui.QGroupBox(self.failover_panel)
        self.failover_group.setObjectName(_fromUtf8("failover_group"))
        self.gridLayout_2 = QtGui.QGridLayout(self.failover_group)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label1_5 = QtGui.QLabel(self.failover_group)
        self.label1_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1_5.setObjectName(_fromUtf8("label1_5"))
        self.gridLayout_2.addWidget(self.label1_5, 0, 0, 1, 1)
        self.failover_sd_line_edit_1 = QtGui.QLineEdit(self.failover_group)
        self.failover_sd_line_edit_1.setObjectName(_fromUtf8("failover_sd_line_edit_1"))
        self.gridLayout_2.addWidget(self.failover_sd_line_edit_1, 0, 1, 1, 1)
        self.label2_4 = QtGui.QLabel(self.failover_group)
        self.label2_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_4.setObjectName(_fromUtf8("label2_4"))
        self.gridLayout_2.addWidget(self.label2_4, 1, 0, 1, 1)
        self.failover_sd_line_edit_2 = QtGui.QLineEdit(self.failover_group)
        self.failover_sd_line_edit_2.setObjectName(_fromUtf8("failover_sd_line_edit_2"))
        self.gridLayout_2.addWidget(self.failover_sd_line_edit_2, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verify_button = QtGui.QPushButton(self.failover_group)
        self.verify_button.setObjectName(_fromUtf8("verify_button"))
        self.horizontalLayout_8.addWidget(self.verify_button)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.failover_group)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.tabWidget.addTab(self.failover_panel, _fromUtf8(""))
        self.test_settings_panel = QtGui.QWidget()
        self.test_settings_panel.setObjectName(_fromUtf8("test_settings_panel"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.test_settings_panel)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.test_settings_group = QtGui.QGroupBox(self.test_settings_panel)
        self.test_settings_group.setObjectName(_fromUtf8("test_settings_group"))
        self.gridLayout_3 = QtGui.QGridLayout(self.test_settings_group)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label1_6 = QtGui.QLabel(self.test_settings_group)
        self.label1_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1_6.setObjectName(_fromUtf8("label1_6"))
        self.gridLayout_3.addWidget(self.label1_6, 0, 0, 1, 1)
        self.invert_pattern_qty_line_edit = QtGui.QLineEdit(self.test_settings_group)
        self.invert_pattern_qty_line_edit.setObjectName(_fromUtf8("invert_pattern_qty_line_edit"))
        self.gridLayout_3.addWidget(self.invert_pattern_qty_line_edit, 0, 1, 1, 1)
        self.label2_5 = QtGui.QLabel(self.test_settings_group)
        self.label2_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_5.setObjectName(_fromUtf8("label2_5"))
        self.gridLayout_3.addWidget(self.label2_5, 1, 0, 1, 1)
        self.packetdrop_downtime_line_edit = QtGui.QLineEdit(self.test_settings_group)
        self.packetdrop_downtime_line_edit.setObjectName(_fromUtf8("packetdrop_downtime_line_edit"))
        self.gridLayout_3.addWidget(self.packetdrop_downtime_line_edit, 1, 1, 1, 1)
        self.label3_2 = QtGui.QLabel(self.test_settings_group)
        self.label3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3_2.setObjectName(_fromUtf8("label3_2"))
        self.gridLayout_3.addWidget(self.label3_2, 2, 0, 1, 1)
        self.packetdrop_uptime_line_edit = QtGui.QLineEdit(self.test_settings_group)
        self.packetdrop_uptime_line_edit.setObjectName(_fromUtf8("packetdrop_uptime_line_edit"))
        self.gridLayout_3.addWidget(self.packetdrop_uptime_line_edit, 2, 1, 1, 1)
        self.label4_2 = QtGui.QLabel(self.test_settings_group)
        self.label4_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label4_2.setObjectName(_fromUtf8("label4_2"))
        self.gridLayout_3.addWidget(self.label4_2, 3, 0, 1, 1)
        self.switchdrop_downtime_line_edit = QtGui.QLineEdit(self.test_settings_group)
        self.switchdrop_downtime_line_edit.setObjectName(_fromUtf8("switchdrop_downtime_line_edit"))
        self.gridLayout_3.addWidget(self.switchdrop_downtime_line_edit, 3, 1, 1, 1)
        self.label5_2 = QtGui.QLabel(self.test_settings_group)
        self.label5_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label5_2.setObjectName(_fromUtf8("label5_2"))
        self.gridLayout_3.addWidget(self.label5_2, 4, 0, 1, 1)
        self.switchdrop_uptime_line_edit = QtGui.QLineEdit(self.test_settings_group)
        self.switchdrop_uptime_line_edit.setObjectName(_fromUtf8("switchdrop_uptime_line_edit"))
        self.gridLayout_3.addWidget(self.switchdrop_uptime_line_edit, 4, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.test_settings_group)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem13)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.test_settings_panel, _fromUtf8(""))
        self.verticalLayout_15.addWidget(self.tabWidget)
        self.tabs_widget_logs = QtGui.QTabWidget(self.centralwidget)
        self.tabs_widget_logs.setTabPosition(QtGui.QTabWidget.West)
        self.tabs_widget_logs.setObjectName(_fromUtf8("tabs_widget_logs"))
        self.tab_info = QtGui.QWidget()
        self.tab_info.setObjectName(_fromUtf8("tab_info"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_info)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.info_text_edit = QtGui.QTextEdit(self.tab_info)
        self.info_text_edit.setReadOnly(True)
        self.info_text_edit.setObjectName(_fromUtf8("info_text_edit"))
        self.verticalLayout.addWidget(self.info_text_edit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabs_widget_logs.addTab(self.tab_info, _fromUtf8(""))
        self.tab_error = QtGui.QWidget()
        self.tab_error.setObjectName(_fromUtf8("tab_error"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_error)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.error_text_edit = QtGui.QTextEdit(self.tab_error)
        self.error_text_edit.setReadOnly(True)
        self.error_text_edit.setObjectName(_fromUtf8("error_text_edit"))
        self.verticalLayout_2.addWidget(self.error_text_edit)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabs_widget_logs.addTab(self.tab_error, _fromUtf8(""))
        self.verticalLayout_15.addWidget(self.tabs_widget_logs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLogs = QtGui.QMenu(self.menubar)
        self.menuLogs.setObjectName(_fromUtf8("menuLogs"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionShow_Logs = QtGui.QAction(MainWindow)
        self.actionShow_Logs.setCheckable(True)
        self.actionShow_Logs.setObjectName(_fromUtf8("actionShow_Logs"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuLogs.addAction(self.actionShow_Logs)
        self.menuLogs.addAction(self.actionClear)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLogs.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.user_label.setBuddy(self.mount_user_box)
        self.password_label.setBuddy(self.mount_passwd_box)
        self.scratch_label.setBuddy(self.scratch_dir_box)
        self.mount_label.setBuddy(self.enable_mount_box)
        self.servername_label.setBuddy(self.server_box1)
        self.workspace_label.setBuddy(self.workspace_box1)
        self.storagegroup_label.setBuddy(self.storage_group_box1)
        self.network_label.setBuddy(self.np_combobox1)
        self.remoteclient_label.setBuddy(self.remote_client_box)
        self.stop_label.setBuddy(self.sotf_box)
        self.developer_label.setBuddy(self.devmode_box)
        self.logging_label.setBuddy(self.log_settings_box)
        self.servername_label_2.setBuddy(self.server_box2)
        self.workspace_label_2.setBuddy(self.workspace_box2)
        self.storagegroup_label_2.setBuddy(self.storage_group_box2)
        self.network_label_2.setBuddy(self.np_combobox2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabs_widget_logs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.on_save)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.on_about)
        QtCore.QObject.connect(self.verify_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_verify_click)
        QtCore.QObject.connect(self.groupcombobox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.populatelist_ctrl)
        QtCore.QObject.connect(self.validate_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_validate_click)
        QtCore.QObject.connect(self.remove_all_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_remove_all_click)
        QtCore.QObject.connect(self.remove_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_remove_click)
        QtCore.QObject.connect(self.add_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_add_click)
        QtCore.QObject.connect(self.copy_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_copy_click)
        QtCore.QObject.connect(self.actionShow_Logs, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.tabs_widget_logs.setVisible)
        QtCore.QObject.connect(self.info_text_edit, QtCore.SIGNAL(_fromUtf8("textChanged()")), MainWindow.on_text_changed_in_logs)
        QtCore.QObject.connect(self.error_text_edit, QtCore.SIGNAL(_fromUtf8("textChanged()")), MainWindow.on_text_changed_in_logs)
        QtCore.QObject.connect(self.tabs_widget_logs, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.on_log_tab_selected)
        QtCore.QObject.connect(self.info_text_edit, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), MainWindow.on_text_clicked_in_logs)
        QtCore.QObject.connect(self.error_text_edit, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), MainWindow.on_text_clicked_in_logs)
        QtCore.QObject.connect(self.actionClear, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.on_clear_logs)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ConfigTD", None))
        self.mount_data_group_box.setTitle(_translate("MainWindow", "Mount Data", None))
        self.user_label.setText(_translate("MainWindow", "Mount User:", None))
        self.password_label.setText(_translate("MainWindow", "Mount Password:", None))
        self.scratch_label.setText(_translate("MainWindow", "Scratch Directory:", None))
        self.mount_label.setText(_translate("MainWindow", "Allow Mounting:", None))
        self.primary_unity_group_box.setTitle(_translate("MainWindow", "Primary Unity", None))
        self.servername_label.setText(_translate("MainWindow", "Virtual Server name:", None))
        self.workspace_label.setText(_translate("MainWindow", "Workspace:", None))
        self.storagegroup_label.setText(_translate("MainWindow", "Storage Group:", None))
        self.network_label.setText(_translate("MainWindow", "Network Provider:", None))
        self.quality_center_group_box.setTitle(_translate("MainWindow", "Quality Center and runsuite.py", None))
        self.remoteclient_label.setText(_translate("MainWindow", "Run on Remote Client:", None))
        self.test_behaviour_group_box.setTitle(_translate("MainWindow", "Test Behavior", None))
        self.stop_label.setText(_translate("MainWindow", "Stop on Test Failure:", None))
        self.developer_label.setText(_translate("MainWindow", "Use Developer Mode:", None))
        self.logging_label.setText(_translate("MainWindow", "Overwrite Log Settings (Hex):", None))
        self.second_unity_group_box.setTitle(_translate("MainWindow", "Second Unity", None))
        self.servername_label_2.setText(_translate("MainWindow", "Virtual Server name:", None))
        self.workspace_label_2.setText(_translate("MainWindow", "Workspace:", None))
        self.storagegroup_label_2.setText(_translate("MainWindow", "Storage Group:", None))
        self.network_label_2.setText(_translate("MainWindow", "Network Provider:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.storage_panel), _translate("MainWindow", "Storage", None))
        self.isisdata_group.setTitle(_translate("MainWindow", "ISIS Data", None))
        self.mcu_label.setText(_translate("MainWindow", "Management Console User:", None))
        self.mcp_label.setText(_translate("MainWindow", "Management Console Password:", None))
        self.sbu_label.setText(_translate("MainWindow", "Switch/Storage Blade User:", None))
        self.sbp_label.setText(_translate("MainWindow", "Switch/Storage Blade Password:", None))
        self.ftp_group.setTitle(_translate("MainWindow", "FTP Server Details", None))
        self.ftpserver_label.setText(_translate("MainWindow", "FTP Server:", None))
        self.ftp_loginname_label.setText(_translate("MainWindow", "FTP Username:", None))
        self.ftp_password_label.setText(_translate("MainWindow", "FTP Password:", None))
        self.licensing_group.setTitle(_translate("MainWindow", "Licensing", None))
        self.system_id_label.setText(_translate("MainWindow", "System ID:", None))
        self.activation_id_label.setText(_translate("MainWindow", "Activation ID:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Licensing (Standby)", None))
        self.sb_activation_id_label.setText(_translate("MainWindow", "System ID:", None))
        self.sb_system_id_label.setText(_translate("MainWindow", "Activation ID:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.isis_panel), _translate("MainWindow", "ISIS", None))
        self.videodata_group.setTitle(_translate("MainWindow", "Video Data", None))
        self.label1.setText(_translate("MainWindow", "COM port:", None))
        self.label2.setText(_translate("MainWindow", "Video Standard:", None))
        self.label3.setText(_translate("MainWindow", "AirO Server:", None))
        self.label4.setText(_translate("MainWindow", "Serial Protocol uses Story TC:", None))
        self.label5.setText(_translate("MainWindow", "VDCP issues STILL after CUE:", None))
        self.storagedata_group.setTitle(_translate("MainWindow", "Storage Data", None))
        self.label1_2.setText(_translate("MainWindow", "Use Static Pattern Feed:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.video_panel), _translate("MainWindow", "Video", None))
        self.verticalGroupBox_5.setTitle(_translate("MainWindow", "Group Name", None))
        self.copy_button.setToolTip(_translate("MainWindow", "Copies the remote clients in the current group to another group", None))
        self.copy_button.setText(_translate("MainWindow", "Copy", None))
        self.validate_button.setToolTip(_translate("MainWindow", "Verifies Test Monkey is running the remote clients in this group", None))
        self.validate_button.setText(_translate("MainWindow", "Validate", None))
        item = self.hoststable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hostname", None))
        item = self.hoststable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Monkey Status", None))
        self.add_button.setToolTip(_translate("MainWindow", "Adds a remote client to the current group", None))
        self.add_button.setText(_translate("MainWindow", "Add", None))
        self.remove_button.setToolTip(_translate("MainWindow", "Removes selected remote clients from the current group", None))
        self.remove_button.setText(_translate("MainWindow", "Remove", None))
        self.remove_all_button.setToolTip(_translate("MainWindow", "Removes all remote clients from the current group", None))
        self.remove_all_button.setText(_translate("MainWindow", "Remove All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.remote_panel), _translate("MainWindow", "Remote Groups", None))
        self.cifs_group.setTitle(_translate("MainWindow", "CIFS Server", None))
        self.label1_3.setText(_translate("MainWindow", "CIFS Server Name:", None))
        self.label2_2.setText(_translate("MainWindow", "ISIS Server Name:", None))
        self.cifs_shares_group.setTitle(_translate("MainWindow", "CIFS Shares", None))
        self.label1_4.setText(_translate("MainWindow", "CIFS Share #1:", None))
        self.label2_3.setText(_translate("MainWindow", "CIFS Share #2:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cifs_panel), _translate("MainWindow", "CIFS Server", None))
        self.failover_group.setTitle(_translate("MainWindow", "Failover System Directors", None))
        self.label1_5.setText(_translate("MainWindow", "First Failover System Director Host Name:", None))
        self.label2_4.setText(_translate("MainWindow", "Second Failover System Director Host Name:", None))
        self.verify_button.setToolTip(_translate("MainWindow", "Verifies the hosts inserted in fields above are available", None))
        self.verify_button.setText(_translate("MainWindow", "Verify", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.failover_panel), _translate("MainWindow", "Failover", None))
        self.test_settings_group.setTitle(_translate("MainWindow", "Test Settings", None))
        self.label1_6.setText(_translate("MainWindow", "Number of times to invert the pattern:", None))
        self.label2_5.setText(_translate("MainWindow", "For packetdrop, number of milliseconds to drop packets on the ports: ", None))
        self.label3_2.setText(_translate("MainWindow", "For packetdrop, number of milliseconds to to allow transmition on the ports: ", None))
        self.label4_2.setText(_translate("MainWindow", "For switchdrop, number of milliseconds to drop packets on the ports:", None))
        self.label5_2.setText(_translate("MainWindow", "For switchdrop, number of milliseconds to to allow transmition on the ports: ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test_settings_panel), _translate("MainWindow", "Test Settings", None))
        self.tabs_widget_logs.setTabText(self.tabs_widget_logs.indexOf(self.tab_info), _translate("MainWindow", "Info", None))
        self.tabs_widget_logs.setTabText(self.tabs_widget_logs.indexOf(self.tab_error), _translate("MainWindow", "Error", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuLogs.setTitle(_translate("MainWindow", "&Logs", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionAbout.setIconText(_translate("MainWindow", "About", None))
        self.actionShow_Logs.setText(_translate("MainWindow", "&Show Logs", None))
        self.actionShow_Logs.setIconText(_translate("MainWindow", "&Show Logs", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setIconText(_translate("MainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionExit.setIconText(_translate("MainWindow", "E&xit", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configtd2_copy_dialog.ui'
#
# Created: Fri Apr  4 16:44:42 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(319, 299)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.list_widget_groups = QtGui.QListWidget(Dialog)
        self.list_widget_groups.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_widget_groups.setSpacing(2)
        self.list_widget_groups.setObjectName(_fromUtf8("list_widget_groups"))
        self.verticalLayout.addWidget(self.list_widget_groups)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Copy remote clients", None))
        self.label.setText(_translate("Dialog", "Which group(s) would you like to copy to?", None))

