# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\FSMigrationMain.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FSMainWindow(object):
    def setupUi(self, FSMainWindow):
        FSMainWindow.setObjectName("FSMainWindow")
        FSMainWindow.resize(565, 250)
        self.centralwidget = QtWidgets.QWidget(FSMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 355))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 3)
        self.lineEdit_host_password = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_host_password.setObjectName("lineEdit_host_password")
        self.gridLayout.addWidget(self.lineEdit_host_password, 11, 1, 1, 1)
        self.lineEdit_src = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_src.setObjectName("lineEdit_src")
        self.gridLayout.addWidget(self.lineEdit_src, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 19, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_migrate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_migrate.setObjectName("btn_migrate")
        self.gridLayout.addWidget(self.btn_migrate, 0, 2, 1, 1)
        self.lineEdit_host_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_host_name.setObjectName("lineEdit_host_name")
        self.gridLayout.addWidget(self.lineEdit_host_name, 8, 1, 1, 1)
        self.btn_recovery = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_recovery.setObjectName("btn_recovery")
        self.gridLayout.addWidget(self.btn_recovery, 2, 2, 1, 1)
        self.label_password = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 11, 0, 1, 1)
        self.btn_src_test = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_src_test.setObjectName("btn_src_test")
        self.gridLayout.addWidget(self.btn_src_test, 8, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 16, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 17, 0, 1, 1)
        self.lineEdit_mcpassword = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_mcpassword.setObjectName("lineEdit_mcpassword")
        self.gridLayout.addWidget(self.lineEdit_mcpassword, 5, 1, 1, 1)
        self.lineEdit_dest = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dest.setObjectName("lineEdit_dest")
        self.gridLayout.addWidget(self.lineEdit_dest, 2, 1, 1, 1)
        self.label_password_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_password_2.setObjectName("label_password_2")
        self.gridLayout.addWidget(self.label_password_2, 5, 0, 1, 1)
        self.btn_dest_test = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_dest_test.setObjectName("btn_dest_test")
        self.gridLayout.addWidget(self.btn_dest_test, 11, 2, 1, 1)
        self.btn_cancel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_username = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_username.setObjectName("label_username")
        self.gridLayout.addWidget(self.label_username, 8, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 21, 0, 1, 3)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 20, 0, 1, 3)
        self.progressBar_source = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_source.setProperty("value", 0)
        self.progressBar_source.setObjectName("progressBar_source")
        self.gridLayout.addWidget(self.progressBar_source, 16, 1, 1, 2)
        self.progressBar_dest = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_dest.setProperty("value", 0)
        self.progressBar_dest.setObjectName("progressBar_dest")
        self.gridLayout.addWidget(self.progressBar_dest, 17, 1, 1, 2)
        FSMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FSMainWindow)
        self.statusbar.setObjectName("statusbar")
        FSMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FSMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FSMainWindow)

    def retranslateUi(self, FSMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FSMainWindow.setWindowTitle(_translate("FSMainWindow", "MainWindow"))
        self.label.setText(_translate("FSMainWindow", "Source System Director:"))
        self.btn_migrate.setText(_translate("FSMainWindow", "Migrate Filesystem"))
        self.btn_recovery.setText(_translate("FSMainWindow", "System Recovery"))
        self.label_password.setText(_translate("FSMainWindow", "Host Password"))
        self.btn_src_test.setText(_translate("FSMainWindow", "Source connection Test"))
        self.label_4.setText(_translate("FSMainWindow", "Source activities"))
        self.label_5.setText(_translate("FSMainWindow", "Destination activities"))
        self.label_password_2.setText(_translate("FSMainWindow", "Management Console Password:"))
        self.btn_dest_test.setText(_translate("FSMainWindow", "Destination connection Test"))
        self.btn_cancel.setText(_translate("FSMainWindow", "Cancel"))
        self.label_2.setText(_translate("FSMainWindow", "Destination System Director:"))
        self.label_username.setText(_translate("FSMainWindow", "Host user name"))

